import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ContextProviders from "./context";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <body>
        <ContextProviders>{children}</ContextProviders>
      </body>
    </html>
  );
}
